# Generated by Django 4.0.2 on 2022-02-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='week',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
