# Generated by Django 4.0.2 on 2022-02-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_chatmessage_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='primary_key',
            field=models.IntegerField(default=1),
        ),
    ]
