# Generated by Django 4.0.2 on 2022-02-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0004_thread_primary_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='infographic',
            field=models.TextField(default=''),
        ),
    ]
