# Generated by Django 4.0.2 on 2022-02-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0006_thread_infographic_link_alter_thread_infographic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='infographic',
        ),
        migrations.AddField(
            model_name='thread',
            name='inforgraphic_text',
            field=models.TextField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='infographic_link',
            field=models.TextField(default='', null=True),
        ),
    ]
