# Generated by Django 4.0.2 on 2022-02-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0007_remove_thread_infographic_thread_inforgraphic_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='infographic_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='inforgraphic_text',
            field=models.TextField(blank=True, default='', max_length=255, null=True),
        ),
    ]
