# Generated by Django 4.0.2 on 2022-02-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0008_alter_thread_infographic_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='inforgraphic_text',
            field=models.TextField(blank=True, default='Acceso a Infografía de esta semana', max_length=255, null=True),
        ),
    ]
